### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by TomasVotruba** [shivammathur/composer-cache#1]
Hi, I just want to say thanky you for your work :heart: 
This is exactly what I look for for all my PHP jobs.

Can't wait for the 1st install :)

**Comment by staabm** [comment]
I want to add another thank you. great job.

just in case you aren't aware of it: there is already a composer-install action, which also handles composer caching - see https://github.com/ramsey/composer-install

**Comment by shivammathur** [comment]
@staabm Yes I'm aware, This is for caching different versions of `composer` phar files, not composer packages. This is done so that `setup-php` does not overload `getcomposer.org`.

**Comment by TomasVotruba** [comment]
Ah, that's good to know. I need the composer package cache one :D the name got me confused
